// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateClusterIgnitionConfigHandlerFunc turns a function with the right signature into a update cluster ignition config handler
type UpdateClusterIgnitionConfigHandlerFunc func(UpdateClusterIgnitionConfigParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateClusterIgnitionConfigHandlerFunc) Handle(params UpdateClusterIgnitionConfigParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateClusterIgnitionConfigHandler interface for that can handle valid update cluster ignition config params
type UpdateClusterIgnitionConfigHandler interface {
	Handle(UpdateClusterIgnitionConfigParams, interface{}) middleware.Responder
}

// NewUpdateClusterIgnitionConfig creates a new http.Handler for the update cluster ignition config operation
func NewUpdateClusterIgnitionConfig(ctx *middleware.Context, handler UpdateClusterIgnitionConfigHandler) *UpdateClusterIgnitionConfig {
	return &UpdateClusterIgnitionConfig{Context: ctx, Handler: handler}
}

/*UpdateClusterIgnitionConfig swagger:route PATCH /clusters/{cluster_id}/ignition-config installer updateClusterIgnitionConfig

Override values in the initial ignition config

*/
type UpdateClusterIgnitionConfig struct {
	Context *middleware.Context
	Handler UpdateClusterIgnitionConfigHandler
}

func (o *UpdateClusterIgnitionConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateClusterIgnitionConfigParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
