// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetClusterIgnitionConfigParams creates a new GetClusterIgnitionConfigParams object
// with the default values initialized.
func NewGetClusterIgnitionConfigParams() *GetClusterIgnitionConfigParams {
	var ()
	return &GetClusterIgnitionConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetClusterIgnitionConfigParamsWithTimeout creates a new GetClusterIgnitionConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetClusterIgnitionConfigParamsWithTimeout(timeout time.Duration) *GetClusterIgnitionConfigParams {
	var ()
	return &GetClusterIgnitionConfigParams{

		timeout: timeout,
	}
}

// NewGetClusterIgnitionConfigParamsWithContext creates a new GetClusterIgnitionConfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetClusterIgnitionConfigParamsWithContext(ctx context.Context) *GetClusterIgnitionConfigParams {
	var ()
	return &GetClusterIgnitionConfigParams{

		Context: ctx,
	}
}

// NewGetClusterIgnitionConfigParamsWithHTTPClient creates a new GetClusterIgnitionConfigParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetClusterIgnitionConfigParamsWithHTTPClient(client *http.Client) *GetClusterIgnitionConfigParams {
	var ()
	return &GetClusterIgnitionConfigParams{
		HTTPClient: client,
	}
}

/*GetClusterIgnitionConfigParams contains all the parameters to send to the API endpoint
for the get cluster ignition config operation typically these are written to a http.Request
*/
type GetClusterIgnitionConfigParams struct {

	/*ClusterID*/
	ClusterID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get cluster ignition config params
func (o *GetClusterIgnitionConfigParams) WithTimeout(timeout time.Duration) *GetClusterIgnitionConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cluster ignition config params
func (o *GetClusterIgnitionConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cluster ignition config params
func (o *GetClusterIgnitionConfigParams) WithContext(ctx context.Context) *GetClusterIgnitionConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cluster ignition config params
func (o *GetClusterIgnitionConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cluster ignition config params
func (o *GetClusterIgnitionConfigParams) WithHTTPClient(client *http.Client) *GetClusterIgnitionConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cluster ignition config params
func (o *GetClusterIgnitionConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the get cluster ignition config params
func (o *GetClusterIgnitionConfigParams) WithClusterID(clusterID strfmt.UUID) *GetClusterIgnitionConfigParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the get cluster ignition config params
func (o *GetClusterIgnitionConfigParams) SetClusterID(clusterID strfmt.UUID) {
	o.ClusterID = clusterID
}

// WriteToRequest writes these params to a swagger request
func (o *GetClusterIgnitionConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
