// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/openshift/assisted-service/models"
)

// NewUpdateClusterIgnitionConfigParams creates a new UpdateClusterIgnitionConfigParams object
// with the default values initialized.
func NewUpdateClusterIgnitionConfigParams() *UpdateClusterIgnitionConfigParams {
	var ()
	return &UpdateClusterIgnitionConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateClusterIgnitionConfigParamsWithTimeout creates a new UpdateClusterIgnitionConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateClusterIgnitionConfigParamsWithTimeout(timeout time.Duration) *UpdateClusterIgnitionConfigParams {
	var ()
	return &UpdateClusterIgnitionConfigParams{

		timeout: timeout,
	}
}

// NewUpdateClusterIgnitionConfigParamsWithContext creates a new UpdateClusterIgnitionConfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateClusterIgnitionConfigParamsWithContext(ctx context.Context) *UpdateClusterIgnitionConfigParams {
	var ()
	return &UpdateClusterIgnitionConfigParams{

		Context: ctx,
	}
}

// NewUpdateClusterIgnitionConfigParamsWithHTTPClient creates a new UpdateClusterIgnitionConfigParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateClusterIgnitionConfigParamsWithHTTPClient(client *http.Client) *UpdateClusterIgnitionConfigParams {
	var ()
	return &UpdateClusterIgnitionConfigParams{
		HTTPClient: client,
	}
}

/*UpdateClusterIgnitionConfigParams contains all the parameters to send to the API endpoint
for the update cluster ignition config operation typically these are written to a http.Request
*/
type UpdateClusterIgnitionConfigParams struct {

	/*ClusterID*/
	ClusterID strfmt.UUID
	/*IgnitionConfigParams*/
	IgnitionConfigParams *models.IgnitionConfigParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update cluster ignition config params
func (o *UpdateClusterIgnitionConfigParams) WithTimeout(timeout time.Duration) *UpdateClusterIgnitionConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update cluster ignition config params
func (o *UpdateClusterIgnitionConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update cluster ignition config params
func (o *UpdateClusterIgnitionConfigParams) WithContext(ctx context.Context) *UpdateClusterIgnitionConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update cluster ignition config params
func (o *UpdateClusterIgnitionConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update cluster ignition config params
func (o *UpdateClusterIgnitionConfigParams) WithHTTPClient(client *http.Client) *UpdateClusterIgnitionConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update cluster ignition config params
func (o *UpdateClusterIgnitionConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the update cluster ignition config params
func (o *UpdateClusterIgnitionConfigParams) WithClusterID(clusterID strfmt.UUID) *UpdateClusterIgnitionConfigParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the update cluster ignition config params
func (o *UpdateClusterIgnitionConfigParams) SetClusterID(clusterID strfmt.UUID) {
	o.ClusterID = clusterID
}

// WithIgnitionConfigParams adds the ignitionConfigParams to the update cluster ignition config params
func (o *UpdateClusterIgnitionConfigParams) WithIgnitionConfigParams(ignitionConfigParams *models.IgnitionConfigParams) *UpdateClusterIgnitionConfigParams {
	o.SetIgnitionConfigParams(ignitionConfigParams)
	return o
}

// SetIgnitionConfigParams adds the ignitionConfigParams to the update cluster ignition config params
func (o *UpdateClusterIgnitionConfigParams) SetIgnitionConfigParams(ignitionConfigParams *models.IgnitionConfigParams) {
	o.IgnitionConfigParams = ignitionConfigParams
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateClusterIgnitionConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID.String()); err != nil {
		return err
	}

	if o.IgnitionConfigParams != nil {
		if err := r.SetBodyParam(o.IgnitionConfigParams); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
